version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "acumen-saas"
s3_bucket = "sam-bootstrap-bucket-49ae2e8f-b182-4a8e-9642-037864535232"
s3_prefix = "serverless-acumen"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"
