version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-cost-per-tenant-lab7"
s3_bucket = "sam-bootstrap-bucket-57d10957-26b7-4d81-8bb3-d3e32f177ccc"
s3_prefix = "serverless-saas-lab7"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"
